### ISSUE TITLE
Restoring Inheritance not being represented correctly?

### ISSUE THREAD

**Issue by B3r** [wcm-io/io.wcm.caconfig.editor#12]
Hey there, 

When using the editor, inherited configurations are displayed like this:
![image](https://user-images.githubusercontent.com/5477168/221654645-660ae3a3-5ae6-441f-af27-dcc774bf68e0.png)

After breaking the inheritance
![image](https://user-images.githubusercontent.com/5477168/221654773-b9ec3e61-1a00-4201-93c0-35e98386da4d.png)

the chain element is represented correctly as broken
![image](https://user-images.githubusercontent.com/5477168/221654940-469a27cb-f2f2-4cac-bbc0-18d291a3fab2.png)

However once it is broken, I cant get it into the first state again.
Even when using `Enable property inheritance` and checking all properties as inherited, the symbol stays as 'broken inheritance'

While this is just 'cosmetics', it might confuse editors though.

Is this behavior intended, or did I miss some configuration somewhere?
Tested with own project and `io.wcm.caconfig.sample-app` on a 6.5 AEM

**Comment by stefanseifert** [comment]
when you got to the inherited configuration, and click on the "delete" button, it should completely erase the inherited config and revert back to inheriting 1:1 the configuration up the hierarchy.

**Comment by B3r** [comment]
My bad, thanks for clearing that up!
