### ISSUE TITLE
Ugly error message appears when using "Quick Publish" for users that do not have replication permission

### ISSUE THREAD

**Issue by mkiti** [wcm-io/io.wcm.caconfig.editor#13]
To replicate our content, a 4 eyes workflow is necessary. This also applies to the context aware configurations. For this, we have removed the replication rights from the authors. As far as I can see, this also works for the ca config, because the request for publication workflow
 is started automatically. However, if the user simply presses the Publish button without having created or changed a configuration beforehand, a rather ugly error message appears. This is a bit confusing for the users. Especially because the "Request for publication" workflow is still started in the background. I also have the feeling that the publish button was greyed out in previous versions if there was no modification (but maybe I'm wrong).

![error_after_click_on_publish](https://user-images.githubusercontent.com/3404045/225088935-9620b969-f49d-446d-981c-935840b90eb4.jpg)

Not to forget, thank you for these great tools.

**Comment by stefanseifert** [comment]
thanks for reporting, i will try to reproduce this

**Comment by stefanseifert** [comment]
with #14 the publication wizard is shown to request for publication when replication permissions are lacking
