### ISSUE TITLE
Trouble including the editor as a sub-package in an AEMaaCS project

### ISSUE THREAD

**Issue by toniedzwiedz** [wcm-io/io.wcm.caconfig.editor#16]
Hello,

I'm trying to get the Context Aware Configuration Editor installed in AEMaaCS by adding it to my `pom.xml` and having it installed with the `filevault-package-maven-plugin`.

I define a module in my project to gather all 3rd party tools and get them installed.

```
<plugin>
    <groupId>org.apache.jackrabbit</groupId>
    <artifactId>filevault-package-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <name>${contentPackage.name}</name>
        <group>${contentPackage.group}</group>
        <packageType>container</packageType>
        <filterSource>src/main/content/META-INF/vault/filter.xml</filterSource>
        <subPackages>
            <subPackage>
                <groupId>io.wcm</groupId>
                <artifactId>io.wcm.caconfig.editor.package</artifactId>
                <filter>true</filter>
            </subPackage>
        </subPackages>
        <embeddedTarget>/apps/cp-aemaacs-prerequisites/install</embeddedTarget>
        <embeddeds>
            <embedded>
                <groupId>io.wcm</groupId>
                <artifactId>io.wcm.caconfig.extensions</artifactId>
            </embedded>
        </embeddeds>
        <allowIndexDefinitions>true</allowIndexDefinitions>
    </configuration>
</plugin>
```

The package is of type `container`. I've done something similar before, on an AEM 6.5 project, with an earlier version of the plugin and the Editor, and it worked fine.

Now I'm getting an error, and a warning at build time, both complaining about the sub-package type.
```
[INFO] Start validating sub package '/home/username/repos/foobarbaz/aem_cloud/prerequisites/target/prerequisites-1.0.0-SNAPSHOT.zip/jcr_root/etc/packages/wcm-io/io.wcm.caconfig.editor.package-1.15.6.zip'...
[INFO] Using 10 validators for package of type MIXED: jackrabbit-accesscontrol (org.apache.jackrabbit.vault.validation.spi.impl.AccessControlValidator),
jackrabbit-filter (org.apache.jackrabbit.vault.validation.spi.impl.AdvancedFilterValidator),
jackrabbit-properties (org.apache.jackrabbit.vault.validation.spi.impl.AdvancedPropertiesValidator),
jackrabbit-docviewparser (org.apache.jackrabbit.vault.validation.spi.impl.DocumentViewParserValidator),
jackrabbit-dependencies (org.apache.jackrabbit.vault.validation.spi.impl.DependencyValidator),
jackrabbit-emptyelements (org.apache.jackrabbit.vault.validation.spi.impl.EmptyElementsValidator),
jackrabbit-mergelimitations (org.apache.jackrabbit.vault.validation.spi.impl.MergeLimitationsValidator),
jackrabbit-oakindex (org.apache.jackrabbit.vault.validation.spi.impl.OakIndexDefinitionValidator),
jackrabbit-packagetype (org.apache.jackrabbit.vault.validation.spi.impl.PackageTypeValidator),
jackrabbit-nodetypes (org.apache.jackrabbit.vault.validation.spi.impl.nodetype.NodeTypeValidator)
[ERROR] ValidationViolation: "jackrabbit-packagetype: Package of type 'CONTAINER' must only contain sub packages of type
'APPLICATION, CONTENT, CONTAINER' but found sub package of type 'MIXED'!",
filePath=jcr_root/etc/packages/wcm-io/io.wcm.caconfig.editor.package-1.15.6.zip/META-INF/vault/properties.xml
[WARNING] ValidationViolation: "jackrabbit-packagetype: Package of type 'MIXED' is legacy. Use one of the other types instead!",
filePath=jcr_root/etc/packages/wcm-io/io.wcm.caconfig.editor.package-1.15.6.zip/META-INF/vault/properties.xml
```

I'm guessing there may have been a change in how strict the Jackrabbit packagetype validator is, which results in the package type used causing problems... Or perhaps I'm just doing something silly.

Perhaps there's a more straightforward way to get it installed neatly?
Penny for your thoughts.

Thanks,
Tomek

**Comment by toniedzwiedz** [comment]
I've worked around this by disabling sub-package validation. 

`<skipSubPackageValidation>true</skipSubPackageValidation>` as a child of the `configuration` element.

**Comment by stefanseifert** [comment]
the content package https://repo1.maven.org/maven2/io/wcm/io.wcm.caconfig.editor.package/ is only for convenience and contains both the OSGi bundle `io.wcm.caconfig.editor` and an example template definition. so it contains a mixture of container and application content, and does not match with any of the given filevault validation "package types". that's why it's using "mixed" as type, which generates the error you observed.

it is best pratice to define you own template definition e.g. as documented here: https://wcm.io/caconfig/editor/usage.html#Defining_the_editor_template and only include the bundle `io.wcm.caconfig.editor` and not the package.

but i agree that might seem a bit confusing and is probably also not ideally documented. we might consider switching to "valid" package types as most new projects will use AEMaaCS and will run into the same problem. but this means we have to provide two separate packages instead of one.

**Comment by stefanseifert** [comment]
disabling the sub-package validation is a possible option, but not recommended as it might hide other problems with sub packages which you need to pay attention for.

**Comment by toniedzwiedz** [comment]
@stefanseifert I agree, this is a workaround. I'm still looking for an actual solution.

>the content package https://repo1.maven.org/maven2/io/wcm/io.wcm.caconfig.editor.package/ is only for convenience and contains both the OSGi bundle io.wcm.caconfig.editor and an example template definition. so it contains a mixture of container and application content, and does not match with any of the given filevault validation "package types". that's why it's using "mixed" as type, which generates the error you observed.
I see, I have my own template definition anyway. Does this mean I don't need the editor package at all?

I thought the bundle only contained the Java back-end and the editor package had the components (with HTL code and such) to render nodes with the `wcm-io/caconfig/editor/components/page/editor` resource type.

**Comment by toniedzwiedz** [comment]
@stefanseifert okay, so assuming I've created my own template, I can probably just get rid of one of those dependencies and their respective sub-packages

```
<plugin>
    <groupId>org.apache.jackrabbit</groupId>
    <artifactId>filevault-package-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <name>${contentPackage.name}</name>
        <group>${contentPackage.group}</group>
        <packageType>container</packageType>
        <filterSource>src/main/content/META-INF/vault/filter.xml</filterSource>
        <embeddedTarget>/apps/cp-aemaacs-prerequisites/install</embeddedTarget>
        <embeddeds>
            <embedded>
                <groupId>io.wcm</groupId>
                <artifactId>io.wcm.caconfig.extensions</artifactId>
            </embedded>
        </embeddeds>
        <allowIndexDefinitions>true</allowIndexDefinitions>
    </configuration>
</plugin>
```
I'll try that.

**Comment by toniedzwiedz** [comment]
Okay, so assuming I have my own template for the configuration page already created, instead of a zip and an OSGi bundle (for extensions), I should use two OSGi bundles. I'll try that, thanks!

**Comment by stefanseifert** [comment]
i've updated the documentation regarding (non-)usage of the ZIP package
https://wcm.io/caconfig/editor/usage.html#Installation
