### ISSUE TITLE
The category dropdown doesn't reflect the actual selection state

### ISSUE THREAD

**Issue by d33t** [wcm-io/io.wcm.caconfig.editor#20]
The "category" dropdown doesn't get updated on page load and on selection and thus doesn't reflect the actual selection state and shows always “all” even if other option is selected. After a page refresh, the last chosen value gets internally selected, the dropdown still shows "all", but the values displayed are for the previously selected category.

To summarize:

1. The filter "category" will always show “all” and never the actual selected category.
2. The previous selected value is stored on client side and when the page is refreshed may lead to confusions where the user see “all” selected but not the expected results for this category.

**Comment by stefanseifert** [comment]
thanks for the report. this sounds like a bug, i will have a look at it (in november)

**Comment by stefanseifert** [comment]
i can confirm the problem on AEM 6.5.18, but it works fine on AEMaaCS SDK.

**Comment by d33t** [comment]
Thanks for taking a look and confirming. It sounds like you have a fix for it already possibly present on the AEMaaCS branch (even if I don't see it)? Or is it the same code that just behaves differently on AEMaaCS?

**Comment by stefanseifert** [comment]
the previous code already worked fine in AEMaaCS SDK.
#21 refactors the code in a way that should work both on AEM 6.5 and AEMaaCS - can you give it a try?

**Comment by d33t** [comment]
I can confirm that your fix works on AEM 6.5.17. Thank you!
