### ISSUE TITLE
We are seeing Quick Publish Wizard to reload constantly after any change in ca config - AEMaaCS

### ISSUE THREAD

**Issue by Kunaldhak** [wcm-io/io.wcm.caconfig.editor#22]
The config seems to be published anyway but the publication wizard keeps reloading intermittently - we are using editor - 1.15.6 .

<img width="956" alt="Screenshot 2023-11-20 153946" src="https://github.com/wcm-io/io.wcm.caconfig.editor/assets/6100901/c017e25c-c725-4503-bb26-ad958c1c30d5">

**Comment by stefanseifert** [comment]
thanks, i can reproduce this issue with 2023.11.14227.20231108T162349Z-231000, it affects both publish buttons in caconfig editor. it does not occur in local AEMaaCS SDK and also not with AEM 6.5. 

in the cloud instance, it only occurs if the "Unified Shell" is enabled (which is default). this is unfortunate as this makes debugging much harder. i noticed that when the publish dialog is opening, it reloads swiftly once before actually clicking on the publish button. i assume this is where the "back" route gets lost.

**Comment by stefanseifert** [comment]
i've created a PR that should fix the problem - i'm still testing it: #23

**Comment by stefanseifert** [comment]
PR is merged, you can try it with version 1.15.7-SNAPSHOT
