### ISSUE TITLE
Add description to checkbox "Enable property inheritance"

### ISSUE THREAD

**Issue by kwin** [wcm-io/io.wcm.caconfig.editor#24]
To most users it is not immediately obvious what the checkbox highlighted below means:
![Screenshot 2024-03-06 at 19 59 52](https://github.com/wcm-io/io.wcm.caconfig.editor/assets/185025/2a1e3c4b-651d-41d7-a790-e65618006f89)
It would be beneficial to add a descriptive text there adding some more context similar to <https://sling.apache.org/documentation/bundles/context-aware-configuration/context-aware-configuration-default-implementation.html#property-inheritance>.

**Comment by kwin** [comment]
This would require adding some more markup after https://github.com/wcm-io/io.wcm.caconfig.editor/blob/1cd96b52cd37c8a10951a0ba818fc4faf061d999/bundle/src/main/resources/angularjs-partials/configTable.html#L18 leveraging the directive https://github.com/wcm-io/io.wcm.caconfig.editor/blob/1cd96b52cd37c8a10951a0ba818fc4faf061d999/bundle/src/main/webapp/app-root/clientlibs/io.wcm.caconfig.editor/js/widgets/description-popup.directive.js#L29.

**Comment by stefanseifert** [comment]
provided PR #30
