### ISSUE TITLE
Expose write location in repository 

### ISSUE THREAD

**Issue by kwin** [wcm-io/io.wcm.caconfig.editor#25]
Currently only the context path is exposed per CAC Editor page
![Screenshot 2024-03-06 at 20 00 37](https://github.com/wcm-io/io.wcm.caconfig.editor/assets/185025/6b846473-21ae-48e0-a4b9-5cc57f9ef7fe)

Next to it there should be the repository resource path being exposed where newly added properties would be persisted. This helps with figuring out permission issues.

**Comment by kwin** [comment]
IMHO this can be achieved by leveraging `org.apache.sling.caconfig.management.multiplexer.ConfigurationResourceResolvingStrategyMultiplexer` with its `getResourcePath(Resource contextResource, "sling:configs", <FQCN of annotated configuration annotation>)`.

**Comment by kwin** [comment]
This would also be useful to provide a better guidance to users lacking write permission in that location (by e.g. disabling the Save button and make all fields read-only)

**Comment by stefanseifert** [comment]
provided PR #31:
it both adds a (i) button to show the actual persist path, and also renders the config details dialog readonly if the current user does not have write permission to this path.
