### ISSUE TITLE
Quick publish and Manage Publication are wrongly redirected

### ISSUE THREAD

**Issue by atkozma** [wcm-io/io.wcm.caconfig.editor#34]
Quick publish and Manage Publication are wrongly redirected, after publish the configs, the user is redirected to Publish page again. Quick publish and Manage Publication can not be canceled. After clicking on Cancel it is redirecting back to the publish screen. The [preview server](https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/sites/authoring/sites-console/previewing-content) is enabled in our environment.

Additional information: It is working with AEMaaCS product version 2023.7, but not with the newer versions.

Quick publish - Steps to Reproduce :
 
1. Click on Context-aware config.
 
2. Add / Update configuration and click on save.
 
3. Click on Quick publish.

Manage Publication - Steps to Reproduce : 

1. Click on Context-aware config.
 
2. Add / Update configuration and click on save.
 
3. Click on Manage Publication
 
4. Click on Next

5. Click on Publish

Actual :: It has to be redirected to the configuration editor or Sites, but instead it is redirected to Publish again.

Expected result:: After successful Quick Publish or after canceling the Quick publish process the user should be redirected to Configuration editor

**Comment by stefanseifert** [comment]
which version of caconfig editor are you using? please note that we fixed some issues with publication wizard handling in version 1.15.8 (#23).

i tested the publication wizard with 1.15.9-SNAPSHOT and AEMaaCS 2024.4.15787.20240404T134829Z and it looked fine, e.g. canceling manage publication works without problem. which AEMaaCS version did you use?

**Comment by atkozma** [comment]
It is working with version 1.15.8. Thank you!
