### ISSUE TITLE
Context Aware Config | Page reloads on initial selection of Path Browser, preventing value selection

### ISSUE THREAD

**Issue by janemartin** [wcm-io/io.wcm.caconfig.editor#37]
Hi Team,

We encounter an issue related to path browser fields. Upon the initial load of the configuration, selecting an item in the path browser triggers a page reload without retaining the selection. However, after this initial reload, subsequent selections work correctly. The issue reoccurs if we reload the page again, specifically affecting the first selection. This behavior applies to previously saved path browser fields, while empty fields behave as expected. 

Environment: AEMaaCS DEV
Version: 2024.6.16971.20240628T122619Z

Please let us know if there is any solution available for this, thanks!

**Comment by stefanseifert** [comment]
PR #39 should fix the problem - please validate it using version 1.16.1-SNAPSHOT of caconfig edtior
