### ISSUE TITLE
The multi options selection order is not displaying but is saving in same order as selected.

### ISSUE THREAD

**Issue by Purandeshwari-10** [wcm-io/io.wcm.caconfig.editor#40]
In configuration, when we create a dropdown which is multiselect and select a particular order while authoring, the order is being saved in effectiveValue of network call but the selected order is not been displayed on config editor after saving.
Please find the below screenshots for reference,
1. Before saving, below is the order I have selected in config,
![BeforeSavingConfig](https://github.com/user-attachments/assets/67470753-3a87-40c7-ba2f-ea9c03d499cb)

2. After saving, below is the order it is showing in config editor
![AfterSavingConfig](https://github.com/user-attachments/assets/d7846be8-695d-45a8-8cfb-0be5d8104ff3)

3. Below are the API value stored in network tab,

![API-DataCall-2](https://github.com/user-attachments/assets/d9df7d1e-0a2d-4fea-9d11-010bac2cc437)
![API-DataCall-1](https://github.com/user-attachments/assets/84888ce9-5ae9-4525-a6a0-a5bb9f654dd4)

**Comment by stefanseifert** [comment]
#41 should fix the problem - can you give it a try?

**Comment by Purandeshwari-10** [comment]
Hi @stefanseifert ,
It is working fine now with the latest changes you have shared, could you please let me know by when will this change be released?

**Comment by stefanseifert** [comment]
thanks for validating - i plan to do make a release early next week
