### ISSUE TITLE
Multifield Text Area widget is shown as text field

### ISSUE THREAD

**Issue by Narendiran100** [wcm-io/io.wcm.caconfig.editor#42]
When I use textarea widgetType as multifield, it is shown as a normal text field instead of a text area.

Ex: @Property(label = "Enter the Page Path", description = "Page Path", property = {
            "widgetType=textarea",
            "textareaRows=20"
    })
    String[] pagePaths();

![image](https://github.com/user-attachments/assets/b182bfa9-4d05-4c0f-bf4d-09cbb0f190bb)

**Comment by stefanseifert** [comment]
PR #43 should fix the problem - can you give it a try?
