### ISSUE TITLE
Unable to publish/preview new assets when it is added to ca config

### ISSUE THREAD

**Issue by srikanthgurram-17** [wcm-io/io.wcm.caconfig.editor#47]
Hi @stefanseifert GoodDay

We have face below issue with ca config editor. we have tested this in 1.16.0 and 1.16.6 versions

steps to reproduce:

1.  upload new image or svg into AemaacS author and do not publish 
2. add this svg/image to a ca config via path field and save it.
3. pubish/preview using quick publish or manage publication

Expected result : image/svg should be published and available in publish server along with config

Actual result:  image is not published along with config. only config is published

Thanks in advance!

**Comment by stefanseifert** [comment]
currently, the is only one custom ReferenceProvider implemented: https://github.com/wcm-io/io.wcm.caconfig.extensions/blob/develop/src/main/java/io/wcm/caconfig/extensions/references/impl/ConfigurationReferenceProvider.java - which allows to publish caconfig together with publishing pages they affect.

there is currently not built-in support in AEM itself or our code that detects references to assets from caconfig. this would be a new feature. we'll have to look into it (or you can come up with a PR).

**Comment by srikanthgurram-17** [comment]
https://github.com/wcm-io/io.wcm.caconfig.extensions/pull/7

**Comment by stefanseifert** [comment]
closing this one as the actual fix has to be done in a different module: https://github.com/wcm-io/io.wcm.caconfig.extensions

continued in the PR https://github.com/wcm-io/io.wcm.caconfig.extensions/pull/7
